sampling_period: 10.0

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

# configuration for classic and predictive lateral control laws
lateral_control:
  selected: back_stepping
  back_stepping:
    gains:
      kp: -0.5
      kd: -1.0
    maximal_omega_d: 0.5

# control setpoint
setpoint:
  desired_linear_speed: 0.5
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

#configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: 10
  rate: 10.

debug: true
