world_package: romea_simulation_gazebo_worlds
world_name: friction_cone.world
# physics:
#   ode:
#     solver:
#       type: quick
#       iters: 50
#       precon_iters: 0
#       sor: 1.3
#       friction_model: cone_model
#     constraints:
#       cfm: 0.0
#       erp: 0.2
#       contact_max_correcting_vel: 100.0
#       contact_surface_layer: 0.001  
#   max_constact: 1 
