name: "lidar"
driver:
  pkg: "sick_scan"
  ip: "192.168.1.112"
  port: "2112"
configuration:
  type: sick
  model: mrs1000
  rate: 50
  resolution: 0.25
geometry:
  parent_link: "base_link"
  xyz: [0.88, 0.0, 0.8635]
  rpy: [0.0, 15.0, 0.0]
records:
  cloud: true
