name: "imu"
namespace: "base"
# driver:
#   package: "xsens_driver"
#   executable: mtnode.py
#   parameters:
#     device: "/dev/ttyUSB0"
#     baudrate: 115200
configuration:
  type: xsens
  model: mti
  rate: 10
geometry:
  parent_link: "base_link"
  xyz: [0.043, 0.0, 0.30]
  rpy: [0.0, 0.0, 0.0]
records:
  data: true
